language: node_js
node_js:
  - 13.2.0
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run build
after_script:
  - npm run coveralls
